# Generated by Django 4.2.30 on 2026-06-19 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_otp_alter_application_id_alter_job_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
