# Generated by Django 4.2.30 on 2026-07-15 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0013_loginotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(blank=True, default='', max_length=20)),
                ('profile_photo', models.CharField(blank=True, default='', max_length=512)),
                ('headline', models.CharField(blank=True, default='', max_length=255)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=20)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('career_level', models.CharField(blank=True, choices=[('Fresher', 'Fresher'), ('Experienced', 'Experienced')], default='', max_length=50)),
                ('total_experience', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('current_company', models.CharField(blank=True, default='', max_length=255)),
                ('current_job_title', models.CharField(blank=True, default='', max_length=255)),
                ('current_salary', models.CharField(blank=True, default='', max_length=100)),
                ('expected_salary', models.CharField(blank=True, default='', max_length=100)),
                ('notice_period', models.CharField(blank=True, default='', max_length=100)),
                ('preferred_job_type', models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Internship', 'Internship'), ('Contract', 'Contract')], default='', max_length=100)),
                ('preferred_work_mode', models.CharField(blank=True, choices=[('On-site', 'On-site'), ('Hybrid', 'Hybrid'), ('Remote', 'Remote')], default='', max_length=100)),
                ('education', models.JSONField(blank=True, default=list, null=True)),
                ('skills', models.JSONField(blank=True, default=list, null=True)),
                ('resume_headline', models.CharField(blank=True, default='', max_length=255)),
                ('resume_last_updated', models.DateField(blank=True, null=True)),
                ('projects', models.JSONField(blank=True, default=list, null=True)),
                ('work_experience', models.JSONField(blank=True, default=list, null=True)),
                ('certifications', models.JSONField(blank=True, default=list, null=True)),
                ('languages', models.JSONField(blank=True, default=list, null=True)),
                ('social_links', models.JSONField(blank=True, default=dict, null=True)),
                ('preferences', models.JSONField(blank=True, default=dict, null=True)),
                ('privacy_settings', models.JSONField(blank=True, default=dict, null=True)),
                ('profile_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
