# Generated by Django 4.2.30 on 2026-07-21 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0017_remove_interview_location_or_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_interviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interview',
            name='meeting_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='interview',
            name='room_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
