# Generated by Django 4.2.30 on 2026-08-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_interview_candidate_interview_meeting_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_match_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_matched_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_missing_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
