# Generated by Django 4.2.30 on 2026-08-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_application_ai_match_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resume_edit_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
