# Generated by Django 6.1 on 2026-09-21 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0028_quiz_access_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('billing_interval', models.CharField(default='month', max_length=20)),
                ('features', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('RECRUITER_VIEWED', 'Recruiter Viewed'), ('SHORTLISTED', 'Shortlisted'), ('RESUME_SHORTLISTED', 'Resume Shortlisted'), ('RESUME_REJECTED', 'Resume Rejected'), ('QUIZ_SCHEDULED', 'Quiz Scheduled'), ('QUIZ_COMPLETED', 'Quiz Completed'), ('QUIZ_PASSED', 'Quiz Passed'), ('QUIZ_NOT_CLEARED', 'Quiz Not Cleared'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('INTERVIEW_COMPLETED', 'Interview Completed'), ('TECHNICAL_INTERVIEW_COMPLETED', 'Technical Interview Completed'), ('TECHNICAL_INTERVIEW_PASSED', 'Technical Interview Passed'), ('TECHNICAL_INTERVIEW_NOT_CLEARED', 'Technical Interview Not Cleared'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected'), ('ON_HOLD', 'On Hold'), ('OFFER_SENT', 'Offer Sent'), ('JOINED', 'Joined')], default='APPLIED', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='technical_interview_mode',
            field=models.CharField(blank=True, default='Video', max_length=50),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('PAST_DUE', 'Past due'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('provider', models.CharField(default='manual', max_length=30)),
                ('provider_customer_id', models.CharField(blank=True, default='', max_length=255)),
                ('provider_subscription_id', models.CharField(blank=True, default='', max_length=255)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='jobs.subscriptionplan')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('provider', models.CharField(default='manual', max_length=30)),
                ('provider_payment_id', models.CharField(blank=True, default='', max_length=255)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PENDING', 'Pending'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='CREATED', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='jobs.subscriptionplan')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_rating', models.PositiveSmallIntegerField(default=0)),
                ('communication_rating', models.PositiveSmallIntegerField(default=0)),
                ('culture_rating', models.PositiveSmallIntegerField(default=0)),
                ('overall_rating', models.PositiveSmallIntegerField(default=0)),
                ('recommendation', models.CharField(choices=[('STRONG_YES', 'Strong yes'), ('YES', 'Yes'), ('MAYBE', 'Maybe'), ('NO', 'No')], default='MAYBE', max_length=20)),
                ('strengths', models.TextField(blank=True, default='')),
                ('concerns', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='jobs.interview')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('interview', 'reviewer'), name='unique_interview_feedback_reviewer')],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('INTERVIEW_24H', 'Interview 24 hours before'), ('INTERVIEW_1H', 'Interview 1 hour before'), ('CUSTOM', 'Custom reminder')], default='CUSTOM', max_length=30)),
                ('scheduled_for', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='jobs.application')),
                ('interview', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='jobs.interview')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_for'],
                'constraints': [models.UniqueConstraint(fields=('interview', 'recipient', 'reminder_type'), name='unique_interview_reminder_recipient_type')],
            },
        ),
    ]
